In [1]:
import numpy as np

In [ ]:
##1. What is a Python library? Why do we use Python libraries?
'''
A Python library is a collection of pre-written code that you can use in your Python programs.
We use them to save time and effort by reusing existing code, making it easier to perform common
tasks or solve specific problems. Libraries provide ready-made solutions, so you don't have to 
start coding from scratch. They make development faster, more efficient, and allow you to tap 
into the collective knowledge of the Python community.

Example:-NumPy,Pandas ,Matplotlib etc
'''

In [ ]:
##2. What is the difference between Numpy array and List?

'''
        List:

(1).Can contain different data types.
(2).Less memory-efficient.
(3).Slower for numerical operations.
(4).General-purpose and versatile.

        NumPy Array:

(1).Must contain elements of the same data type.
(2).More memory-efficient.
(3).Faster for numerical operations.
(4).Specialized for numerical computations.

'''

In [2]:
'''
3. Find the shape, size and dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]
'''
import numpy as np

a=[[1, 2, 3, 4],
   [5, 6, 7, 8],
   [9, 10, 11, 12]]
arr =np.asarray(a)
arr
print(arr.size) ## for size
print(arr.shape)## for shape
print(arr.ndim)## for dimension

12
(3, 4)
2


In [3]:
'''4. Write python code to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]
'''
import numpy as np

arr1 =[[1, 2, 3, 4],
        [5, 6, 7, 8],
       [9, 10, 11, 12]]
arr1[0] ## To access the first row

[1, 2, 3, 4]

In [4]:
'''
5. How do you access the element at the third row and fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]

'''
import numpy as np

arr=[[1, 2, 3, 4],
     [5, 6, 7, 8],
     [9, 10, 11, 12]]
arr[2][3]

12

In [5]:
'''
6. Write code to extract all odd-indexed elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]
'''
import numpy as np

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
arr[:,1::2]

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [6]:
##7. How can you generate a random 3x3 matrix with values between 0 and 1?
import numpy as np

arr=np.random.rand(3,3)
arr

array([[0.45268513, 0.13969248, 0.68665596],
       [0.3662242 , 0.67680884, 0.18871396],
       [0.30698441, 0.08758081, 0.58016257]])

In [ ]:
##8. Describe the difference between np.random.rand and np.random.randn?
'''
       np.random.rand                                    |         np.random.randn       
                                                         |
   Generates random numbers from a uniform distribution  | Generates random numbers from a standard normal distribution (mean=0,standard deviation=1).        
over the interval [0, 1).                                |


'''

In [7]:
'''
9. Write code to increase the dimension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]
'''
import numpy as np

arr=np.array([[1, 2, 3, 4],
               [5, 6, 7, 8],
            [9, 10, 11, 12]])
arr1=np.expand_dims(arr, axis=0)
arr1
print(arr1.ndim)

3


In [29]:
'''
10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]
'''
import numpy as np
arr=np.array([[1, 2, 3, 4],
             [5, 6, 7, 8],
             [9, 10, 11, 12]])
arr.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [20]:
'''
11. Consider the following matrix:
Matrix A: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B: [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]

Perform the following operation using Python1

1. Index wise multiplication
2.Matrix multiplication
3.Add both the matrics
4.Subtract mattrix B from A
5.Divide matrix B by A
'''
import numpy as np

Matrix_A= ([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
Matrix_B= ([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10, 11, 12]])
arr1=np.array(Matrix_A)
arr2=np.array(Matrix_B)

a=arr1*arr2
##Matrix multiplication not possible because n!=p
c=arr1 + arr2
d=arr2 - arr1
e=arr2/arr1
print(a)

print(c)
print(d)
print(e)

[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [ ]:
##12. Which function in Numpy can be used to swap the byte order of an array?
'''
In NumPy, the function "np.ndarray.byteswap()" can be used to swap the byte order (endianess) of
an array. This function is applicable for arrays with integer or floating-point data types
'''

In [ ]:
##13. What is the significance of the np.linalg.inv function?

"""
The 'np.linalg.inv' function in NumPy is used to find the inverse of a square matrix.
The inverse of a matrix is like the "opposite" matrix that, when multiplied by the 
original matrix, gives the identity matrix.

The significance of finding the inverse is that it helps in solving systems of linear equations,
understanding the properties of the matrix, and performing certain mathematical operations in 
linear algebra. It's a useful tool when dealing with mathematical problems involving matrices.
"""

In [ ]:
##14. What does the np.reshape function do, and how is it use?

"""
The 'np.reshape' function in NumPy is like rearranging the elements of a box to change its shape 
without adding or removing any items.
"""

In [30]:
##15. What is broadcasting in Numpy?
"""
NumPy broadcasting is like a smart way for arrays of different shapes to work together
without explicitly making them the same shape. It automatically adjusts their shapes to 
perform operations smoothly.
"""
import numpy as np


A = np.array([[1, 2, 3],
              [4, 5, 6]])
A + 5




array([[ 6,  7,  8],
       [ 9, 10, 11]])